[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
kinferry_guard = "HZiw1u9BoKkdhppnN22HJzXUQJDca2yMeDY8wqywSdEs"

[programs.localnet]
kinferry_guard = "Fg6PaFpoGXkYsidMpWxTWqkZsZ7FEfcYkgMQhgFQYjM"

[provider]
cluster = "devnet"
wallet = "C:/Users/arche/.config/solana/veztra-deploy.json"

[scripts]
test = "npm run test:guard"

[hooks]
