import {NextResponse} from "next/server";
import Groq from "groq-sdk";
import {z} from "zod";

const requestSchema=z.object({instruction:z.string().min(3).max(500)});
const modelSchema=z.object({recipient:z.string().nullable().optional(),amount:z.coerce.number().positive().nullable().optional(),purpose:z.string().nullable().optional(),schedule:z.string().nullable().optional(),question:z.string().nullable().optional()});

export async function POST(request:Request){const parsed=requestSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({status:"needs_clarification",question:"What transfer should I prepare?"},{status:400});const instruction=parsed.data.instruction;if(!process.env.GROQ_API_KEY)return NextResponse.json(localParse(instruction));try{const groq=new Groq({apiKey:process.env.GROQ_API_KEY});const completion=await groq.chat.completions.create({model:"llama-3.3-70b-versatile",temperature:0,messages:[{role:"system",content:"Extract a remittance draft. Never guess an ambiguous recipient. Return JSON with recipient, amount, purpose, schedule, and question. Use null when unknown."},{role:"user",content:instruction}],response_format:{type:"json_object"}});const raw=JSON.parse(completion.choices[0]?.message?.content||"{}");const model=modelSchema.safeParse(raw);if(!model.success||!model.data.recipient||!model.data.amount)return NextResponse.json({status:"needs_clarification",question:model.success&&model.data.question||"Which verified recipient and amount should I use?"});return NextResponse.json({status:"ready",recipient:model.data.recipient.toLowerCase(),amount:model.data.amount,purpose:model.data.purpose||instruction,schedule:model.data.schedule||"now"})}catch{return NextResponse.json(localParse(instruction))}}

function localParse(instruction:string){const amount=instruction.match(/(?:\$\s*|\b)([\d.]+)(?:\s*dollars?)?/i)?.[1];const names=["maria","adi","lina"].filter(name=>instruction.toLowerCase().includes(name));if(!amount||names.length!==1)return{status:"needs_clarification",question:!amount?"How much should be sent?":"Which verified recipient do you mean?"};return{status:"ready",recipient:names[0],amount:Number(amount),purpose:instruction,schedule:instruction.toLowerCase().includes("next")?"future":"now"}}
