"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {AnimatePresence,motion,useReducedMotion} from "framer-motion";
import {CalendarClock,History,LayoutDashboard,Send,ShieldCheck,Users} from "lucide-react";
import {AgentConfirmationToast} from "./agent-confirmation-toast";
import {Logo} from "./logo";
import {WalletControl} from "./wallet-control";

const nav=[["/dashboard","Overview",LayoutDashboard],["/recipients","Recipients",Users],["/transfer/new","New transfer",Send],["/recurring","Recurring",CalendarClock],["/history","History",History]] as const;

export function AppShell({children}:{children:React.ReactNode}){const path=usePathname();const reduce=useReducedMotion();return <div className="min-h-screen bg-[#f4f7f5]"><AgentConfirmationToast/><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-[#dce7e2] bg-white p-5 lg:block"><Link href="/"><Logo/></Link><nav className="mt-12 space-y-1">{nav.map(([href,label,Icon])=><Link key={href} href={href} className={"focus-ring flex min-h-11 items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium "+(path===href||path.startsWith(href+"/")?"bg-[#e9f4f0] text-[#0f665f]":"text-[#667671] hover:bg-[#f4f7f5]")}><Icon size={18}/>{label}</Link>)}</nav><div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-[#112f2b] p-4 text-white"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-[#7bd8c6]"><ShieldCheck size={15}/>Program live</div><p className="mono mt-3 break-all text-[10px] leading-4 text-white/70">HZiw1u9B...wqywSdEs</p><Link href="/proof" className="mt-3 inline-block text-xs font-semibold text-[#7bd8c6]">Open chain proof</Link></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-30 flex min-h-20 items-center justify-between border-b border-[#dce7e2] bg-[#f4f7f5]/90 px-5 py-3 backdrop-blur-xl md:px-8"><div className="lg:hidden"><Logo compact/></div><div className="hidden items-center gap-2 text-xs font-semibold uppercase tracking-[.14em] text-[#60706c] lg:flex"><span className="h-2 w-2 rounded-full bg-[#18a778]"/>Solana devnet · live program</div><WalletControl/></header><AnimatePresence mode="wait" initial={false}><motion.main key={path} initial={reduce?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={reduce?undefined:{opacity:0,y:-6}} transition={{duration:.22,ease:[.22,1,.36,1]}} className="mx-auto max-w-7xl p-5 pb-24 md:p-8">{children}</motion.main></AnimatePresence><nav className="fixed inset-x-0 bottom-0 z-40 flex justify-around border-t border-[#dce7e2] bg-white p-2 lg:hidden">{nav.slice(0,4).map(([href,label,Icon])=><Link key={href} href={href} className="focus-ring flex min-h-11 flex-col items-center justify-center gap-1 px-2 py-1 text-[10px] text-[#5e6d69]"><Icon size={19}/>{label}</Link>)}</nav></div></div>}
