"use client";
import Link from "next/link";
import {CalendarClock,CircleDollarSign,Clock3,Copy,Plus,Send,ShieldCheck,Users} from "lucide-react";
import {recipients,transfers} from "@/lib/data";
import {RecipientInvite} from "./recipient-invite";
import {Status} from "./status";
import {TransferComposer} from "./transfer-composer";

const card="rounded-2xl border border-[#dce7e2] bg-white";
function Heading({eyebrow,title,body,action}:{eyebrow:string;title:string;body:string;action?:React.ReactNode}){return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#0f766e]">{eyebrow}</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.045em]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#657570]">{body}</p></div>{action}</div>}

export function ProductView({view}:{view:string}){
 if(view==="dashboard")return <><Heading eyebrow="Friday, July 24" title="Your rail is clear" body="Every scheduled and manual transfer runs through the same four safeguards." action={<Link className="inline-flex items-center gap-2 rounded-full bg-[#103d38] px-5 py-3 text-sm font-semibold text-white" href="/transfer/new"><Send size={17}/>New transfer</Link>}/><div className="grid gap-4 md:grid-cols-3">{[[CircleDollarSign,"30-day movement","$412.00","$588 remains"],[Users,"Verified recipients","2","1 awaiting confirmation"],[ShieldCheck,"Blocked mistakes","3","All stopped before signing"]].map(([Icon,label,value,note])=><div className={card+" p-6"} key={String(label)}><div className="flex items-center justify-between"><span className="text-sm text-[#6b7b76]">{String(label)}</span><Icon className="text-[#0f766e]" size={20}/></div><p className="mt-7 text-3xl font-semibold">{String(value)}</p><p className="mt-2 text-xs text-[#778680]">{String(note)}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className={card+" p-6"}><div className="flex justify-between"><h2 className="font-semibold">Recent transfers</h2><Link href="/history" className="text-sm font-semibold text-[#0f766e]">View all</Link></div><div className="mt-5 divide-y divide-[#e6eeeb]">{transfers.map(t=><div key={t.tx} className="grid grid-cols-[1fr_auto] gap-4 py-4 sm:grid-cols-[1fr_120px_120px]"><div><p className="font-medium">{t.recipient}</p><p className="mt-1 text-xs text-[#74837e]">{t.date} · {t.tx}</p></div><div><p className="font-semibold">{t.amount}</p><p className="text-xs text-[#74837e]">{t.receives}</p></div><span className="hidden self-center justify-self-end rounded-full bg-[#e7f5ef] px-3 py-1 text-xs font-semibold text-[#137a59] sm:block">{t.status}</span></div>)}</div></section><section className={card+" overflow-hidden"}><div className="bg-[#112f2b] p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#79d8c5]">Next run</p><p className="mt-8 text-3xl font-semibold">$180.00</p><p className="mt-2 text-sm text-white/60">to Maria · July 29</p></div><div className="p-6"><div className="flex gap-3"><Clock3 className="text-[#d89117]"/><div><p className="text-sm font-semibold">Policy rechecks at runtime</p><p className="text-xs text-[#74837e]">No limit is reserved in advance.</p></div></div></div></section></div></>;
 if(view==="recipients")return <><Heading eyebrow="Address book" title="Verified people, not pasted wallets" body="A new address stays unusable until the recipient confirms it outside your session." action={<Link href="/recipients/new" className="inline-flex items-center gap-2 rounded-full bg-[#103d38] px-5 py-3 text-sm font-semibold text-white"><Plus size={17}/>Add recipient</Link>}/><div className="grid gap-4">{recipients.map(r=><div key={r.id} className={card+" flex flex-col gap-5 p-5 sm:flex-row sm:items-center"}><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e5efec] font-semibold text-[#315b54]">{r.initials}</span><div className="flex-1"><p className="font-semibold">{r.name}</p><p className="mt-1 text-sm text-[#70807b]">{r.country} · <span className="mono">{r.wallet}</span></p></div><Status verified={r.verified}/><button aria-label="Copy wallet" className="rounded-xl border border-[#dce7e2] p-3 text-[#60706c]"><Copy size={17}/></button></div>)}</div></>;
 if(view==="recipient-new")return <><Heading eyebrow="Recipient verification" title="Invite the person who owns the wallet" body="You provide contact details; they independently confirm the wallet before it can enter your allowlist."/><div className="max-w-2xl"><RecipientInvite/></div></>;
 if(view==="transfer")return <><Heading eyebrow="Guarded transfer" title="Write it plainly. Review it precisely." body="The parser prepares a draft. It cannot bypass recipient, policy, quote, or duplicate checks."/><TransferComposer/></>;
 if(view==="recurring")return <><Heading eyebrow="Schedules" title="Recurring without blind trust" body="Each run starts from zero and must pass the current policy, recipient, quote, and duplicate checks." action={<button className="inline-flex items-center gap-2 rounded-full bg-[#103d38] px-5 py-3 text-sm font-semibold text-white"><Plus size={17}/>New schedule</button>}/><div className="grid gap-4 md:grid-cols-2">{[["Maria Santos","$180","Monthly · 29th","Jul 29, 2026","Active"],["Adi Pratama","$75","Every 2 weeks","Paused","Paused"]].map(([name,amount,cadence,next,status])=><article key={name} className={card+" p-6"}><div className="flex justify-between"><div><p className="font-semibold">{name}</p><p className="mt-1 text-sm text-[#71817c]">{cadence}</p></div><span className={"rounded-full px-3 py-1 text-xs font-semibold "+(status==="Active"?"bg-[#e7f5ef] text-[#137a59]":"bg-[#edf0ef] text-[#64736f]")}>{status}</span></div><p className="mt-8 text-3xl font-semibold">{amount}</p><div className="mt-5 flex items-center gap-2 border-t border-[#e4ece9] pt-5 text-sm text-[#667671]"><CalendarClock size={17}/>Next: {next}</div></article>)}</div></>;
 return <><Heading eyebrow="Immutable trail" title="Every decision leaves a record" body="Settled entries are never edited. Corrections become linked adjustment records."/><div className={card+" overflow-hidden"}>{transfers.map(t=><div key={t.tx} className="grid gap-2 border-t border-[#e4ece9] px-6 py-5 md:grid-cols-[1fr_140px_180px_100px]"><span className="font-medium">{t.recipient}<small className="block text-[#74837e]">{t.date}</small></span><span>{t.amount}<small className="block text-[#74837e]">{t.receives}</small></span><span className="mono text-sm text-[#0f766e]">{t.tx}</span><span className="text-sm font-semibold text-[#137a59]">{t.status}</span></div>)}</div></>
}
